apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: eyego-app
  namespace: eyego
  name: eyego-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eyego-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eyego-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - image: ${DOCKER_REGISTRY}/${DOCKER_REPO}:${BUILD_NUMBER}
        name: eyego-container
        ports:
        - containerPort: 3000
        resources: 
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always