apiVersion: v1
kind: Service
metadata:
  namespace: eyego
  name: eyego-service
spec:
  selector:
    app.kubernetes.io/name: eyego-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
